export const professionTypes = [
  'Cardiologist (Heart Specialist)',
  'Dermatologist (Skin Specialist)',
  'General Practitioner (GP) (Primary Care Doctor)',
  'Gastroenterologist (Digestive System Specialist)',
  'Endocrinologist (Hormone and Gland Specialist)',
  'Hematologist (Blood Specialist)',
  'Infectious Disease Specialist',
  'Internist (Internal Medicine Specialist)',
  'Nephrologist (Kidney Specialist)',
  'Neurologist (Brain and Nervous System Specialist)',
  'Obstetrician/Gynecologist (OB/GYN) (Women’s Health Specialist)',
  'Oncologist (Cancer Specialist)',
  'Ophthalmologist (Eye Specialist)',
  'Orthopedic Surgeon (Bone and Muscle Specialist)',
  'Otolaryngologist (ENT) (Ear, Nose, and Throat Specialist)',
  'Pediatrician (Children’s Health Specialist)',
  'Plastic Surgeon',
  'Psychiatrist (Mental Health Specialist)',
  'Pulmonologist (Lung Specialist)',
  'Radiologist (Imaging Specialist)',
  'Rheumatologist (Joint and Autoimmune Specialist)',
  'Surgeon (General Surgeon)',
  'Urologist (Urinary System Specialist)',
];
